---
- hosts: all
  become: yes
  vars_files:
  - ./env_variables.yml
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes

    - name: disable ufw & install docker
      shell: |
        ufw disable

    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker apt repository for stable version
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker
      apt:
        name: "{{ docker_packages }}"
        state: latest
        update_cache: yes

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        group: docker

    - name: Add an apt signing key for Kubernetes
      shell: |
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes

    - name: Install Kubernetes binaries
      apt:
        name: "{{ k8s_packages }}"
        state: present
        update_cache: yes

    - name: Starting and Enabling the required services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services }}"

    - name: Allow Network Ports in Firewalld
      firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: yes
        immediate: yes
      with_items: "{{ master_ports if ('kubernetes-master-nodes' in group_names) else worker_ports }}"
      vars:
        ansible_python_interpreter: '/usr/bin/python3'

    - name: Enabling Bridge Firewall Rule
      shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"



